/**
 * XP, levels, streaks and badges are configuration, not logic baked into
 * UI components. Every XP award must be recorded as an xp_transactions row
 * server-side — never a direct mutation of a user's XP total.
 */
export const XP_AWARDS = {
  check_in: 10,
  attend_event: 25,
  create_post: 5,
  join_challenge: 5,
  complete_challenge: 50,
  join_crew: 15,
  explore_new_place: 20,
  meaningful_engagement_received: 2,
  complete_onboarding: 100,
} as const;

export type XpAwardReason = keyof typeof XP_AWARDS;

/**
 * Level thresholds: cumulative XP required to reach each level. Index 0 =
 * level 1 (0 XP). Generated by a quadratic curve (threshold(i) = 50*i*(i+1))
 * rather than hand-picked, so leveling never hard-caps — a fixed 11-entry
 * array would have left every user above ~5800 XP permanently at "Lvl 11".
 */
export const LEVEL_THRESHOLDS: readonly number[] = Array.from({ length: 100 }, (_, i) => 50 * i * (i + 1));

export function levelForXp(totalXp: number): number {
  let level = 1;
  for (let i = 1; i < LEVEL_THRESHOLDS.length; i++) {
    if (totalXp >= LEVEL_THRESHOLDS[i]!) {
      level = i + 1;
    }
  }
  return level;
}

export interface LevelProgress {
  level: number;
  xpIntoLevel: number;
  xpForLevel: number;
  xpToNextLevel: number;
  /** 0-1. 1 when at the highest defined level (no further threshold to progress toward). */
  progressRatio: number;
}

/** Everything a "Lvl N, X XP to next level" progress bar needs, derived from total XP alone. */
export function getLevelProgress(totalXp: number): LevelProgress {
  const level = levelForXp(totalXp);
  const floor = LEVEL_THRESHOLDS[level - 1] ?? 0;
  const ceiling = LEVEL_THRESHOLDS[level];

  if (ceiling === undefined) {
    return { level, xpIntoLevel: totalXp - floor, xpForLevel: 0, xpToNextLevel: 0, progressRatio: 1 };
  }

  const xpForLevel = ceiling - floor;
  const xpIntoLevel = totalXp - floor;
  return {
    level,
    xpIntoLevel,
    xpForLevel,
    xpToNextLevel: ceiling - totalXp,
    progressRatio: xpForLevel > 0 ? xpIntoLevel / xpForLevel : 1,
  };
}

export const STREAK_TYPES = ["outside", "social", "explorer", "event"] as const;

export type StreakType = (typeof STREAK_TYPES)[number];

/** Minimum gap enforced between check-ins to prevent spam/abuse. */
export const CHECK_IN_RATE_LIMIT_SECONDS = 120;

export const BADGE_SLUGS = [
  "first_check_in",
  "explorer",
  "social_starter",
  "weekend_warrior",
  "crew_builder",
  "event_regular",
  "early_vyber",
] as const;

export type BadgeSlug = (typeof BADGE_SLUGS)[number];

/**
 * Display-only emoji per badge — there's no real badge artwork, so the DB's
 * `icon_url` stays null and this fills the icon slot in the UI instead.
 */
export const BADGE_ICONS: Record<BadgeSlug, string> = {
  first_check_in: "📍",
  explorer: "🧭",
  social_starter: "📣",
  weekend_warrior: "🌆",
  crew_builder: "🏗️",
  event_regular: "🎟️",
  early_vyber: "🌟",
};

/**
 * How recent a check-in has to be for a profile to count as "outside now"
 * (is_outside_now / get_city_outside_count / get_crew_outside_count in
 * 20261008000200_social_graph_and_presence.sql). Display-only constant —
 * the window itself is enforced server-side, this just documents it.
 */
export const PRESENCE_WINDOW_HOURS = 4;
